### ISSUE TITLE
color picker should not be blue

### ISSUE THREAD

**Issue by harthur** [thedarkone/firepicker#1]
This extension is awesome, but the blue color is distracting from the color picking, it clashes with the colors, and doesn't look like it's part of Firebug.

It should be a neutral gray color, like 'window' or some other shade of gray.

**Comment by thedarkone** [comment]
You have a point. I'll change the colors in the next release.

**Comment by thedarkone** [comment]
Pushed out 1.3.1 that is "blue-less" :).

If anyone feels like improving on my crude (non) design, open chrome://firepicker/content/color-picker.html to experiment on the dialog.
