### ISSUE TITLE
Doesn't work?

### ISSUE THREAD

**Issue by DRuggeri** [thedarkone/firepicker#11]
Hello;
   I am on Firefox 5.0 and have installed this extension along with Firebug 1.7.3. I can confirm on two systems (Windows 7 and Windows XP) that after installation, this addon doesn't seem to do anything. I am not sure what combination of things might contribute to this, but when in the CSS pane and hovering over a color the standard firebug color swatch shows up. When clicking on it, or highlighting it, I have only the option to edit as if the extension is not installed.

   I'd like to get this working since it would be quite nice, so let me know if there are any steps I can do take to assist with troubleshooting or figuring this out.
## 

Daniel

**Comment by thedarkone** [comment]
Hey,

Firepicker doesn't work in CSS tab, only in the HTML tab. I'm planning on fixing this when I have the time.
