### ISSUE TITLE
Doesn't work?

### ISSUE THREAD

**Issue by Tekylla** [thedarkone/firepicker#13]
I have the latest version of Firefox and Firebug and also the firepicker.
And I was trying to change color and nothing appear.

I have about 5 plug ins to Firebug and  more plug ins to firefox is it possible the compability?

**Comment by thedarkone** [comment]
Hello @Tekylla,

can you please post your Firefox, Firebug and operating system versions?

**Comment by thedarkone** [comment]
No update from the submitter, closing.
