### ISSUE TITLE
firepicker box hide the half of the color value 

### ISSUE THREAD

**Issue by decembre** [thedarkone/firepicker#16]
Like the title say , the box where i see the color hide the half of the edit color value in firebug...so  it's more difficult to edit it.

Am i alone?

**Comment by verbatim** [comment]
http://www.flickr.com/photos/31792685@N02/6544697623/in/photostream

The color editor obscures the CSS. I fixed it by going to 

MAC:
/Users/[user_name]/Library/Application Support/Firefox/Profiles/[random].default/extensions/firepicker@thedarkone/chrome/skin/classic/css-attribute-dialog.css

WIN7:
C:\Users\[user_name]\AppData\Roaming\Mozilla\Firefox\Profiles\[random].default\extensions\firepicker@thedarkone\chrome\skin\classic\css-attribute-dialog.css

WIN-XP
C:\Documents and Settings\[user_name]\Application Data\Mozilla\Firefox\Profiles\[random].default\extensions\firepicker@thedarkone\chrome\skin\classic\css-attribute-dialog.css

and changing the margins on the class .firepicker_color_container

from

  margin-top: -10px;
  margin-left: 4px;

to: margin:0px;

*\* followup:

should also revise:

.new_dom_layout .firepicker_color_container

to: margin:0px;

**Comment by thedarkone** [comment]
Hello,

this has been fixed in the newest version.

Thanks!
