### ISSUE TITLE
Firepicker not working in detached mode on Macintosh - similar to issue #14

### ISSUE THREAD

**Issue by verbatim** [thedarkone/firepicker#19]
I am still having this issue:
http://www.flickr.com/photos/31792685@N02/6609717765/

Actual color appears underneath the TEXT or HEX color, but the color picker never appears and no ability to change the color

My current specs are:

Firefox 8.01
Firebug 1.84
Firepicker 1.37
Macintosh 10.6.8
Firebug window separated

**Comment by thedarkone** [comment]
I'm unable to repro this.

I gather this only happens in the detached firebug window (ie. everything works fine in the non-detached mode)?

**Comment by verbatim** [comment]
Yes, it was only occurring detached. But I see what the problem is now. I have this other plugin
https://addons.mozilla.org/en-US/firefox/addon/friendly-bug

FriendlyBug, which adds several features to FireBug as well as adding features to FirePicker. Look at the feature list:
2. add's option to firepicker popup to change color between hex and rgba

Once I turn off FriendlyBug, this issue #19 goes away. Maybe you can work with this plugin developer to fix the problem.

I also wrote him a note, pointing to this bug.

**Comment by verbatim** [comment]
The person working on FriendlyBug is working to fix the conflicts, but it might be cool if firepicker naturally had capability to switch color between HEX, RGB, RGBA.

**Comment by thedarkone** [comment]
There's now a transparency dragger that switches to RGBA when necessary in the newest version.
