### ISSUE TITLE
Named colors in gradients are not recognized

### ISSUE THREAD

**Issue by SebastianZ** [thedarkone/firepicker#21]
FirePicker does not recognize the some color values in `-moz-linear-gradient()` and `-moz-radial-gradient()`.

Examples:
- For `-moz-linear-gradient(top, red, blue, green)`, only the color picker for red and blue is displayed.
- For `-moz-linear-gradient(center center, red, blue, green)`, only the color picker for red and blue is displayed.
- For `-moz-linear-gradient(red, blue, green)`, only the color picker for blue is displayed.

I tested this with FF 10.0.2 + FB 1.9.1 + FP 1.4.0 on Win7.

Sebastian

**Comment by thedarkone** [comment]
Thank you! This should be fixed in the next version (it might take a couple of days before it gets reviewed by Mozilla and become available as an automatic update).

**Comment by SebastianZ** [comment]
Works fine for me. Thanks a lot for the fast fix!

Sebastian
