### ISSUE TITLE
Does not recognize more than one RGBA value

### ISSUE THREAD

**Issue by nathanjosiah** [thedarkone/firepicker#22]
For example, "background:-moz-linear-gradient(rgba(247, 247, 247, 0.51), rgba(181, 202, 220, 0.48)) repeat scroll 0 0 transparent" only the second value is available to change with the picker

**Comment by thedarkone** [comment]
Thank you! This should be fixed in the next version (it might take a couple of days before it gets reviewed by Mozilla and become available as an automatic update).
