### ISSUE TITLE
Checker for semi-transparent colors

### ISSUE THREAD

**Issue by SebastianZ** [thedarkone/firepicker#26]
While the color picker already has a checker background for the alpha value, there is none for the colors inside the list of colors.
Semi-transparent colors should be shown exactly like in the color infotip Firebug shows when hovering them.

Sebastian

**Comment by thedarkone** [comment]
It took me a good 5 minutes, before I figured out what you mean :), I'll fix that.

**Comment by SebastianZ** [comment]
Sorry, I'm not a native speaker, so I looked up the word "checker". I meant the chess board pattern used as background.

Sebastian
