### ISSUE TITLE
Bug with FirePicker and FireBug

### ISSUE THREAD

**Issue by innovaweb-dev** [thedarkone/firepicker#28]
Hello,

I have no problem with FireBug.
But when I install FirePicker. Can not edit or add CSS rules.
Also "autocompletion" no longer works.

I disable all other modules.
Remove and install FireBug and FirePicker.

Firebug 1.10.4
FirePicker 1.4.2
16.0.1 FireFox
Windows 7 (6.1 SP1) 64x

Thank you for your help.
And sorry for my english, I'm french.

**Comment by thedarkone** [comment]
Hello,

what you are describing looks to be a repeat of issue #23. Can you try repeating the steps suggested by @SebastianZ in that ticket?

**Comment by innovaweb-dev** [comment]
A big thank you, it works.
I create a new profile FireFox.

https://getfirebug.com/wiki/index.php/FAQ#Installing_in_a_clean_profile

**Comment by SebastianZ** [comment]
I can see such problems when the accessibility enhancements are enabled. This can be done via Firebug Menu > _Options_ > _Enable Accessibility Enhancements_.

Test case:
1. Open Firebug on https://getfirebug.com/
2. Switch to the _HTML_ panel and there to the _Style_ side panel
3. Check the option _Enable Accessibility Enhancements_
4. Inside the _Style_ side panel click the value (`#333333`) of the `color` property inside the `body` rule
    => The inline editor opens and shows the value of the color inside of it. (OK)
5. Press Escape
6. Click the value again

=> The inline editor is opened, but the value is not shown inside of it. (BUG)

Similar things happen when you try to add a new property or edit another property. Sometimes you'll even see a previously entered property name in the value field. So it looks like the inline editors get mixed up.

Sebastian

**Comment by SebastianZ** [comment]
Tested using FF 16.0.2 + FB 1.10.6 and it works fine for me. Thanks!

> Big thanks to @SebastianZ for tracking this down!

You're welcome.

Sebastian
