### ISSUE TITLE
The picker does not open correctly in a detached Firebug window

### ISSUE THREAD

**Issue by olleolleolle** [thedarkone/firepicker#4]
There's a brief flicker, and then nothing.

**Comment by thedarkone** [comment]
Yeah, I know there are some issues with a detached Firebug window. I tried to fix some of them in  http://github.com/thedarkone/firepicker/commit/783c5fe38dfafa0462a88eccedcffe3a1e8b7492

**Comment by thedarkone** [comment]
Hey,

this should be fixed in the newest version.

Thanks!
