### ISSUE TITLE
Plugin breaks completely in Firefox 4 Beta 9

### ISSUE THREAD

**Issue by jdesai** [thedarkone/firepicker#7]
Firepicker is one of my favorite plugins and it was having no problems even with the beta versions of Firefox 4. But as soon as I upgraded to the latest Firefox 4 Beta 9 , Firepicker stopped working. Hovering/clicking on color codes in Firebug does not open Firepicker. I am using the version 1.3.2 with Firebug 1.7a8

Waiting for a fix. Thanks again for a great time-saving plugin.

**Comment by thedarkone** [comment]
I've fixed a Firebug 1.7 incompatibility issue and uploaded a new (1.3.3) version. As soon as it passes a review by Mozilla staff (this might take a couple of days though) it will become available for download.

**Comment by jdesai** [comment]
That's cool. Thanks for the quick fix.
