### ISSUE TITLE
Broken on Firebug 1.7X.0b1?

### ISSUE THREAD

**Issue by svoop** [thedarkone/firepicker#8]
Firepicker doesn't work on my Mac with Firebug 1.7X.0b1, clicking on a color value has no effect at all. (That's on the current FF 4 RC1.)

**Comment by thedarkone** [comment]
Hey,

everything seems to be working fine for me (I'm on Mac as well). Has your Firepicker's version been auto-updated to 1.3.3?

**Comment by thedarkone** [comment]
Closing.

**Comment by svoop** [comment]
Hiya

I'm sorry for not replying earlier - I've been on vacation. Just tried Firepicker 1.3.4 on Firebug 1.7.0. Hovering over color values shows a float with the color, but no colorpicker. It seems, Firepicker is not really loaded.

**Comment by svoop** [comment]
I've tried with only Firebug and Firepicker, yet Firepicker still doesn't load. The error console shows the following warning when Firefox starts:

Warning: Warning: Ignoring obsolete chrome registration modifier 'xpcnativewrappers=no'.
Source File: /Users/sschwyn/Library/Application Support/Firefox/Profiles/7y75a6c3.default/extensions/firepicker@thedarkone.xpi:chrome.manifest
Line: 1

Could not read chrome manifest file '/Applications/Firefox.app/Contents/MacOS/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}/chrome.manifest'.

**Comment by thedarkone** [comment]
Hey,

a couple of things, that might be going wrong...

Firepicker only works when editing color values on the Firebug's "HTML" tab, it doesn't work on the "CSS" tab (I need to get around fixing that).

You need to click the CSS's property value as if you wanted to change it manually, Firepicker then displays a list of colors it detected like this: [pic1](https://static.addons.mozilla.net/img/uploads/previews/full/37/37991.png?modified=1255710510) clicking on any of the colors should display the color picker dialog as shown here: [pic2](https://static.addons.mozilla.net/img/uploads/previews/full/37/37992.png?modified=1255710511)

**Comment by svoop** [comment]
Hiya

I wasn't aware of the current limitation to the HTML tab, indeed, Firepicker works like a charm there. Thanks for your help!
