### ISSUE TITLE
FirePicker does not recognize the first color value in -moz-linear-gradient()

### ISSUE THREAD

**Issue by ChristianSiegert** [thedarkone/firepicker#9]
FirePicker does not recognize the first color value in `-moz-linear-gradient()`.

Examples:
- For `-moz-linear-gradient(#AAA, #BBB)`, only the color picker for the second color (#BBB) is displayed.
- For `-moz-linear-gradient(#AAA, #BBB, #CCC)`, only the color picker for the second and third color (#BBB and #CCC) is displayed.

A workaround I found: Inserting a space before the first color, e.g. `-moz-linear-gradient( #AAA, #BBB)` makes the color picker for the first color (#AAA) appear.

**Comment by thedarkone** [comment]
Fix an issue with the CSS splitting regexp. Closed by b2f548055f4dd38cc56821dd64b627dbdf1b751a
